name: smart_news_app
description: "App de Noticias Inteligente con Flutter y Provider"
publish_to: 'none' # Evita que se publique accidentalmente en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencias principales
  http: ^1.2.2                # Para consumir APIs REST
  provider: ^6.1.2            # Para la gestión de estado
  shared_preferences: ^2.2.2  # Para guardar favoritos o configuraciones localmente
  google_fonts: ^6.2.1        # Para personalizar las fuentes de texto
  animations: ^2.0.10         # Para animaciones suaves y transiciones modernas
  cupertino_icons: ^1.0.8     # Iconos de estilo iOS
  url_launcher: ^6.3.0        # Para abrir enlaces externos en el navegador

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2        # Buenas prácticas y advertencias de código

flutter:
  uses-material-design: true   # Activa el uso de iconos Material Design
